[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.near-mainnet]
shard = "primary"
protocol = "near"
provider = [
  { label = "near-mainnet", details = { type = "firehose", url = "https://mainnet.near.streamingfast.io", token = "$STREAMING_FAST_API_TOKEN" }},
]

[chains.near-battlefield]
shard = "primary"
protocol = "near"
provider = [
  { label = "near-battlefield", details = { type = "firehose", url = "http://localhost:15042" }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
